#!/bin/bash
# Generates src/version.h based on git commit count.
# Versioning: each commit increments patch. Patch resets at 10 -> bumps minor.
# Minor resets at 10 -> bumps major. So 100 commits = v3.0.0.

MAJOR_BASE=2          # current major series
COMMITS_AT_MAJOR=15    # how many commits had passed when we tagged this major

if [ -d .git ]; then
    TOTAL=$(git rev-list --count HEAD 2>/dev/null || echo 0)
else
    TOTAL=0
fi

OFFSET=$((TOTAL - COMMITS_AT_MAJOR))
if [ "$OFFSET" -lt 0 ]; then OFFSET=0; fi

MAJOR=$((MAJOR_BASE + OFFSET / 100))
MINOR=$(( (OFFSET / 10) % 10 ))
PATCH=$((OFFSET % 10))

VERSION="v${MAJOR}.${MINOR}.${PATCH}"
SHORTSHA=$(git rev-parse --short HEAD 2>/dev/null || echo "nocommit")

cat > src/version.h << EOF
#ifndef VERSION_H
#define VERSION_H

/* Auto-generated by gen_version.sh - do not edit by hand.
 * Version is derived from git commit count.
 */

#define MYMISU_VERSION  "${VERSION}"
#define MYMISU_GIT_SHA  "${SHORTSHA}"
#define MYMISU_BUILD    "${VERSION} (${SHORTSHA})"

#endif
EOF

echo "Generated src/version.h: ${VERSION} (${SHORTSHA})"
