#ifndef VERSION_H
#define VERSION_H

/* Auto-generated by gen_version.sh - do not edit by hand.
 * Version is derived from git commit count.
 */

#define MYMISU_VERSION  "v2.0.0"
#define MYMISU_GIT_SHA  "ffcfaf4"
#define MYMISU_BUILD    "v2.0.0 (ffcfaf4)"

#endif
