#ifndef VERSION_H
#define VERSION_H

/* Auto-generated by gen_version.sh - do not edit by hand.
 * Version is derived from git commit count.
 */

#define MYMISU_VERSION  "v2.0.5"
#define MYMISU_GIT_SHA  "834d194"
#define MYMISU_BUILD    "v2.0.5 (834d194)"

#endif
